husky/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from doctors.views import (
    index, get_excluded_dates_by_doctor, get_time_by_doctor_and_date
)

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', index, name='index'),
    url(r'^gedbd/(?P<doctor_id>\d+)/$', get_excluded_dates_by_doctor),
    url(r'^gatbdd/(?P<doctor_id>\d+)/(?P<date>\d{2}\.\d{2}\.\d{4})/$',
        get_time_by_doctor_and_date),
]

doctors/models.py
from django.conf import settings
from django.db import models, IntegrityError
from django.db.models import Count
from django.utils.datetime_safe import datetime
from .utils import today, format_date


class Doctor(models.Model):
    name = models.CharField('имя', max_length=255)

    class Meta:
        verbose_name = 'врача'
        verbose_name_plural = 'врачи'
        ordering = ('name', )

    def __str__(self):
        return self.name


class RecordManager(models.Manager):
    def excluded_dates(self, doctor_id=None):
        if not doctor_id:
            raise IntegrityError('Doctor ID is not specified.')
        qs = self.get_queryset().values('date').annotate(
            day_records=Count('date')
        ).filter(
            date__gte=today(),
            doctor=doctor_id,
            day_records=len(range(*settings.WORKING_HOURS))
        ).order_by('name')
        return qs

    def available_time(self, doctor_id=None, day=None):
        if not doctor_id:
            raise IntegrityError('Doctor ID is not specified.')
        if not day:
            raise IntegrityError('Day is not specified.')
        qs = self.get_queryset().filter(
            doctor=doctor_id, date=day).values('time')
        all_hours = set(range(*settings.WORKING_HOURS))
        if day == today():
            now = datetime.now()
            all_hours ^= set(range(settings.WORKING_HOURS[0], now.hour + 1))
            qs = qs.filter(time__gte=now)
        qs = {
            'hours': list(all_hours ^ {record['time'].hour for record in qs})
        }
        return qs


class Record(models.Model):
    doctor = models.ForeignKey(
        Doctor, verbose_name='Врач', related_name='records'
    )
    date = models.DateField('Дата')
    time = models.TimeField('Время')
    name = models.CharField('Ф.И.О. пациента', max_length=255)

    objects = RecordManager()

    class Meta:
        verbose_name = 'запись на прием'
        verbose_name_plural = 'записи на прием'
        ordering = ('date', 'time')
        unique_together = ('date', 'time', 'doctor')

    def __str__(self):
        return 'Запись к {0} на {1:%H:%M} {2}'.format(
            self.doctor.name, self.time, format_date(self.date)
        )

doctors/forms.py
from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from .models import Record
from .utils import today, normalize_weekdays


class RecordModelForm(ModelForm):
    def clean(self):
        cleaned_data = super(RecordModelForm, self).clean()

        time = cleaned_data.get('time')
        date = cleaned_data.get('date')
        doctor = cleaned_data.get('doctor')

        if time:
            try:
                assert time.hour in range(*settings.WORKING_HOURS)
                assert time.hour in Record.objects.available_time(
                    doctor, date).get('hours')
            except AssertionError:
                raise ValidationError("Выберите правильное время.")

        if date:
            try:
                assert date
                assert date >= today()
                assert date.isoweekday() not in normalize_weekdays(
                    *settings.DISABLED_WEEKDAYS)
                assert date not in Record.objects.excluded_dates(doctor)
            except AssertionError:
                raise ValidationError("Выберите правильную дату.")

    class Meta:
        model = Record
        fields = ('doctor', 'date', 'time', 'name')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ф.И.О.'
            }),
            'doctor': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Имя врача',
            }),
            'date': forms.TextInput(attrs={
                'readonly': True,
                'class': 'form-control',
            }),
            'time': forms.Select(attrs={
                'class': 'form-control',
            }),

        }

doctors/views.py
from django.conf import settings
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.utils.datetime_safe import datetime
from .forms import RecordModelForm
from .models import Record
from .utils import format_date


def index(request):
    form = RecordModelForm(request.POST or None)
    if form.is_valid():
        data = form.save()
        messages.success(
            request,
            'Вы успешно записаны ко врачу {0}'
            ' на {1:%H:%M} {1:%d.%m.%Y}'.format(
                data.doctor.name, datetime.combine(data.date, data.time)
            )
        )
        return redirect(reverse('index'))
    return render(request, 'base.html', {'form': form, 'settings': settings})


def get_excluded_dates_by_doctor(request, doctor_id):
    qs = Record.objects.excluded_dates(doctor_id)
    exclude_dates = {'dates': [format_date(result['date']) for result in qs]}
    return JsonResponse(exclude_dates)


def get_time_by_doctor_and_date(request, doctor_id, date):
    date = format_date(date, reverse=True)
    available_time = Record.objects.available_time(doctor_id, date)
    return JsonResponse(available_time)

templates/base.html
{% load staticfiles %}
{% load l10n %}
<!DOCTYPE html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Запись ко врачу</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.standalone.min.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/locales/bootstrap-datepicker.ru.min.js"></script>
</head>
<body>
<div class="container center-block">
    <div class="page-header">
        <h1>Запись ко врачу</h1>
    </div>
    {% if messages %}
        <ul class="messages list-unstyled">
            {% for message in messages %}
                <li{% if message.tags %} role="alert" class="alert alert-{{ message.tags }}"{% endif %}>
                    {{ message }}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <form method="post" action="" class="form-horizontal">
            {{ form.non_field_errors }}
            <div class="form-group{% if form.name.errors %} has-error{% endif %}">
                <label for="id_name" class="col-sm-2 control-label">
                    Ваше имя
                </label>

                <div class="col-sm-4">
                    {{ form.name }}
                </div>
                {% if form.name.errors %}
                    <span class="help-block">{% for error in form.name.errors %}{{ error }}{% endfor %}</span>
                {% endif %}
            </div>
            <div class="form-group{% if form.doctor.errors %} has-error{% endif %}">
                <label for="id_doctor" class="col-sm-2 control-label">Выберите врача:</label>

                <div class="col-sm-4">
                    {{ form.doctor }}
                </div>
                {% if form.doctor.errors %}
                    <span class="help-block">{% for error in form.doctor.errors %}{{ error }}{% endfor %}</span>
                {% endif %}
            </div>
            <hr>
            <div class="form-group{% if form.date.errors %} has-error{% endif %}" id="id_date">
                <label for="id_date" class="col-sm-2 control-label">Выберите дату:</label>

                <div class="col-sm-4">
                    {{ form.date }}
                </div>
                {% if form.date.errors %}
                    <span class="help-block">{% for error in form.date.errors %}{{ error }}{% endfor %}</span>
                {% endif %}
            </div>
            <div class="form-group{% if form.time.errors %} has-error{% endif %}" id="id_time">
                <label for="id_time" class="col-sm-2 control-label">Выберите время:</label>

                <div class="col-sm-4">
                    {{ form.time }}
                </div>
                {% if form.time.errors %}
                    <span class="help-block">{% for error in form.time.errors %}{{ error }}{% endfor %}</span>
                {% endif %}
            </div>
            {% csrf_token %}
            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-2">
                    <button type="submit" class="btn btn-default">Записаться</button>
                </div>
            </div>
        </form>

        <script>
            $(document).ready(function () {
                var doctor_select = $("select#id_doctor");
                var date_input = $("input#id_date");
                var time_select = $("select#id_time");

                var init_datepicker = function (doctor_select) {
                    date_input.datepicker('remove');
                    var format = 'dd.mm.yyyy', lang = 'ru';
                    var url = "/gedbd/" + doctor_select.val() + "/";
                    $.getJSON(url, function (exclude_dates) {
                        date_input.datepicker({
                            daysOfWeekDisabled: {{ settings.DISABLED_WEEKDAYS|escapejs }},
                            language: lang,
                            autoclose: true,
                            inline: true,
                            startDate: $.fn.datepicker.DPGlobal.formatDate(new Date(), format, lang),
                            format: format,
                            startView: 0,
                            weekStart: 1,
                            datesDisabled: exclude_dates.dates
                        });
                    });
                    if (!date_input.is(':visible')) {
                        $("#id_date").show();
                    }
                };

                // Nasty datepicker .change() bug
                var _change = '';

                if (!doctor_select.val()) {
                    $("#id_date").hide();
                } else {
                    init_datepicker(doctor_select);
                }
                if (!date_input.val()) {
                    $("#id_time").hide();
                }

                doctor_select.change(function () {
                    if (!$(this).val()) {
                        date_input.datepicker('remove');
                        date_input.val('');
                        date_input.change();
                        $("#id_date").hide();
                    } else {
                        date_input.val('');
                        date_input.change();
                        init_datepicker(doctor_select);
                        if (!date_input.is(':visible')) {
                            $("#id_date").show();
                        }
                    }
                });

                date_input.change(function () {
                    if (!($(this).val() && doctor_select.val())) {
                        time_select.empty();
                        $("#id_time").hide()
                    } else {
                        if (_change !== $(this).val()) {
                            _change = $(this).val();
                            var url = "/gatbdd/" + doctor_select.val() + "/" + $(this).val() + "/";
                            $.getJSON(url, function (available_hours) {
                                var options = '';
                                for (var i = 0; i < available_hours.hours.length; i++) {
                                    options += '<option value="' + available_hours.hours[i] + ':00:00">'
                                            + available_hours.hours[i] + ':00</option>';
                                }
                                time_select.html(options);
                                if (!time_select.is(':visible')) {
                                    $("#id_time").show();
                                }
                            });
                        }
                    }
                });
            });
        </script>
    {% endif %}
</div>
</body>
</html>